#!/usr/bin/perl
# PODNAME: software-license
# ABSTRACT: command-line interface to Software::License

use strict;
use warnings;
use App::Software::License;

App::Software::License->new_with_options->run;

__END__

=pod

=encoding UTF-8

=for :stopwords Florian Ragwitz Karen Etheridge Randy Stauner

=head1 NAME

software-license - command-line interface to Software::License

=head1 VERSION

version 0.02

=head1 AUTHOR

Florian Ragwitz <rafl@debian.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2009 by Florian Ragwitz.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
